# Generated by Django 6.0.3 on 2026-03-21 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_choices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choicemember',
            name='final_score',
            field=models.IntegerField(default=0, help_text='Tanlov tugaganida muzlatilgan ball'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='started_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
