# Generated by Django 6.0.3 on 2026-04-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_choice_description_choice_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
