# Generated by Django 6.0.3 on 2026-03-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='newslog',
            options={'ordering': ['-created_at']},
        ),
    ]
