# Generated by Django 6.0.3 on 2026-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='data_card_audio/'),
        ),
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='module_images/'),
        ),
    ]
