# Generated by Django 6.0.3 on 2026-03-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_category_image_datacard_audio_module_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='image',
        ),
    ]
