# Generated by Django 6.0.3 on 2026-03-20 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='coin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'module')},
        ),
    ]
