# Generated by Django 6.0.3 on 2026-03-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_module_coin_module_score_alter_score_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacard',
            name='plan',
        ),
        migrations.AddField(
            model_name='module',
            name='plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
