# Generated by Django 6.0.3 on 2026-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_remove_datacard_plan_module_plan_delete_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
