# Generated by Django 5.2.12 on 2026-04-04 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_feedbackmodule_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='module',
        ),
        migrations.CreateModel(
            name='ModuleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('is_admin_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_comments', to='education.module')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='education.modulecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ModuleComment',
                'verbose_name_plural': 'ModuleComments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_questions', to='education.module')),
            ],
            options={
                'verbose_name': 'ModuleQuestion',
                'verbose_name_plural': 'ModuleQuestions',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='FeedbackModule',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
