# Generated by Django 5.2.18 on 2026-10-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0005_question_questionlike"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=64)),
                ("url", models.URLField(max_length=1000, unique=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("text", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("skipped", "O'tkazib yuborilgan"),
                            ("rejected", "AI rad etgan"),
                            ("pending", "Tasdiq kutilmoqda"),
                            ("approved", "Tasdiqlangan"),
                            ("declined", "Admin rad etgan"),
                            ("failed", "Xato"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("ai_reason", models.CharField(blank=True, max_length=500)),
                ("draft_title", models.CharField(blank=True, max_length=255)),
                ("draft_content", models.TextField(blank=True)),
                ("telegram_messages", models.JSONField(blank=True, default=list)),
                ("reviewed_by", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "news",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_items",
                        to="news.news",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
