# Generated by Django 5.2.18 on 2026-10-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collecteditem",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
