# Generated by Django 6.0.3 on 2026-04-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emergencynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencynotification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emergency_notifications/'),
        ),
    ]
