# Generated by Django 5.2.12 on 2026-04-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emergencynotification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencynotification',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
